# Generated by Django 3.1 on 2025-09-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20250920_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_added',
            new_name='is_ordered',
        ),
    ]
